name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2            
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build homer --file Dockerfile --tag ninharp/homer:$(date +%s)
